import React from "react";

export const Index = () => {
   return (
    <table className="table table-bordered border-secundary">
  <thead>
    <tr className="container-center">
      <th>Hora</th>
      <th>Lunes</th>
      <th>Martes</th>
      <th>Miércoles</th>
      <th>Jueves</th>
      <th>Viernes</th>
      <th>Sábado</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        6:00
        7:00
        8:00
        9:00
        10:00
        11:00
        12:00
        13:00
        14:00
        15:00
        16:00
        17:00
        18:00
        19:00
      </td>
      <td>
        Disponible
        Disponible
        Ocupado
        Ocupado
        Disponible
        Disponible
        Ocupado
        Ocupado
        Disponible
        Disonible
        Disponible
        Disponible
        Disponible
        Disponible
      </td>
      <td>
        Disponible
        Disponible
        Disponible
        Disponible
        Disponible
        Disponible
        Ocupado
        Ocupado
        Disponible
        Disonible
        Disponible
        Disponible
        Disponible
        Disponible
      </td>
      <td>
        Disponible
        Disponible
        Disponible
        Disponible
        Disponible
        Disponible
        Ocupado
        Ocupado
        Disponible
        Disonible
        Disponible
        Disponible
        Disponible
        Disponible
      </td>
      <td>
        Disponible
        Disponible
        Disponible
        Disponible
        Disponible
        Disponible
        Ocupado
        Ocupado
        Disponible
        Disonible
        Disponible
        Disponible
        Disponible
        Disponible
      </td>
      <td>
        Disponible
        Disponible
        Ocupado
        Ocupado
        Disponible
        Disponible
        Ocupado
        Ocupado
        Disponible
        Disonible
        Disponible
        Disponible
        Ocupado
        Ocupado
      </td>
      <td>
        Ocupado
        Ocupado
        Disponible
        Disponible
        Disponible
        Disponible
        Ocupado
        Ocupado
        Ocupado
        Ocupado
        Disponible
        Disponible
        Disponible
        Disponible
      </td>
    </tr>
  </tbody>
</table>
   )}